# Generated by Django 4.0.2 on 2022-03-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbussi',
            name='category',
            field=models.CharField(max_length=25),
        ),
    ]
